// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using simple_bloomberg_terminal.Data;

#nullable disable

namespace simple_bloomberg_terminal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603213908_MoveFilingLinkToReview")]
    partial class MoveFilingLinkToReview
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CompanyEvent", b =>
                {
                    b.Property<long>("CompaniesId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventsId")
                        .HasColumnType("bigint");

                    b.HasKey("CompaniesId", "EventsId");

                    b.HasIndex("EventsId");

                    b.ToTable("CompanyEvent");
                });

            modelBuilder.Entity("CountryEvent", b =>
                {
                    b.Property<long>("CountriesId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventsId")
                        .HasColumnType("bigint");

                    b.HasKey("CountriesId", "EventsId");

                    b.HasIndex("EventsId");

                    b.ToTable("CountryEvent");
                });

            modelBuilder.Entity("CountryTradeBloc", b =>
                {
                    b.Property<long>("CountriesId")
                        .HasColumnType("bigint");

                    b.Property<long>("TradeBlocsId")
                        .HasColumnType("bigint");

                    b.HasKey("CountriesId", "TradeBlocsId");

                    b.HasIndex("TradeBlocsId");

                    b.ToTable("CountryTradeBloc");
                });

            modelBuilder.Entity("EventTradeBloc", b =>
                {
                    b.Property<long>("EventsId")
                        .HasColumnType("bigint");

                    b.Property<long>("TradeBlocsId")
                        .HasColumnType("bigint");

                    b.HasKey("EventsId", "TradeBlocsId");

                    b.HasIndex("TradeBlocsId");

                    b.ToTable("EventTradeBloc");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("AsOf")
                        .HasColumnType("date");

                    b.Property<string>("Cik")
                        .HasColumnType("longtext");

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("GrossMargin")
                        .HasColumnType("double");

                    b.Property<int?>("Industry")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<double?>("RevenueTotal")
                        .HasColumnType("double");

                    b.Property<int>("Sector")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.CostSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<int>("CostBase")
                        .HasColumnType("int");

                    b.Property<int?>("DataSource")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double?>("Percentage")
                        .HasColumnType("double");

                    b.Property<long?>("RelatedCompanyId")
                        .HasColumnType("bigint");

                    b.Property<double?>("Value")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RelatedCompanyId");

                    b.ToTable("CostSources");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("GdpUsd")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<long?>("Population")
                        .HasColumnType("bigint");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double?>("RiskRating")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.CountryAdvantage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CountryDetailsCountryId")
                        .HasColumnType("bigint");

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CountryDetailsCountryId");

                    b.HasIndex("CountryId");

                    b.ToTable("CountryAdvantages");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.CountryChallenge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CountryDetailsCountryId")
                        .HasColumnType("bigint");

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CountryDetailsCountryId");

                    b.HasIndex("CountryId");

                    b.ToTable("CountryChallenges");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.CountryDetails", b =>
                {
                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MarketPosition")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CountryId");

                    b.ToTable("CountryDetails");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("ImpactScore")
                        .HasColumnType("double");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.Filing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessionNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FilingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Form")
                        .HasColumnType("longtext");

                    b.Property<string>("PrimaryDocUrl")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AccessionNumber")
                        .IsUnique();

                    b.HasIndex("CompanyId");

                    b.ToTable("Filings");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.GdpSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CountryDetailsCountryId")
                        .HasColumnType("bigint");

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("GdpUsd")
                        .HasColumnType("double");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryDetailsCountryId");

                    b.HasIndex("CountryId");

                    b.ToTable("GdpSnapshots");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.RevenueSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<int?>("DataSource")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double?>("Percentage")
                        .HasColumnType("double");

                    b.Property<long?>("RelatedCompanyId")
                        .HasColumnType("bigint");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<double?>("Value")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RelatedCompanyId");

                    b.ToTable("RevenueSources");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.SourceFieldReview", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CostSourceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Field")
                        .HasColumnType("int");

                    b.Property<long?>("FilingId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Mark")
                        .HasColumnType("int");

                    b.Property<string>("Rationale")
                        .HasColumnType("longtext");

                    b.Property<string>("ReferencePointer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReferenceSnapshot")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReferencedValue")
                        .HasColumnType("longtext");

                    b.Property<int>("Relation")
                        .HasColumnType("int");

                    b.Property<long?>("RevenueSourceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReviewerModel")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("FilingId");

                    b.HasIndex("CostSourceId", "Field")
                        .IsUnique();

                    b.HasIndex("RevenueSourceId", "Field")
                        .IsUnique();

                    b.ToTable("SourceFieldReviews", t =>
                        {
                            t.HasCheckConstraint("CK_SourceFieldReview_OneSource", "(RevenueSourceId IS NULL) <> (CostSourceId IS NULL)");
                        });
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.TradeBloc", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("FoundedDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TradeBlocs");
                });

            modelBuilder.Entity("CompanyEvent", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompaniesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CountryEvent", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Country", null)
                        .WithMany()
                        .HasForeignKey("CountriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CountryTradeBloc", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Country", null)
                        .WithMany()
                        .HasForeignKey("CountriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.TradeBloc", null)
                        .WithMany()
                        .HasForeignKey("TradeBlocsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventTradeBloc", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.TradeBloc", null)
                        .WithMany()
                        .HasForeignKey("TradeBlocsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.Company", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Country", "Country")
                        .WithMany("Companies")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.CostSource", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Company", "Company")
                        .WithMany("CostSources")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Company", "RelatedCompany")
                        .WithMany("CostFromDependents")
                        .HasForeignKey("RelatedCompanyId");

                    b.Navigation("Company");

                    b.Navigation("RelatedCompany");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.CountryAdvantage", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.CountryDetails", null)
                        .WithMany("Advantages")
                        .HasForeignKey("CountryDetailsCountryId");

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Country", "Country")
                        .WithMany("Advantages")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.CountryChallenge", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.CountryDetails", null)
                        .WithMany("Challenges")
                        .HasForeignKey("CountryDetailsCountryId");

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Country", "Country")
                        .WithMany("Challenges")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.CountryDetails", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Country", "Country")
                        .WithOne("Details")
                        .HasForeignKey("simple_bloomberg_terminal.Models.Entities.CountryDetails", "CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.Filing", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.GdpSnapshot", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.CountryDetails", null)
                        .WithMany("GdpHistory")
                        .HasForeignKey("CountryDetailsCountryId");

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Country", "Country")
                        .WithMany("GdpHistory")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.RevenueSource", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Company", "Company")
                        .WithMany("RevenueSources")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Company", "RelatedCompany")
                        .WithMany("RevenueFromDependents")
                        .HasForeignKey("RelatedCompanyId");

                    b.Navigation("Company");

                    b.Navigation("RelatedCompany");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.SourceFieldReview", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.CostSource", "CostSource")
                        .WithMany("Reviews")
                        .HasForeignKey("CostSourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Filing", "Filing")
                        .WithMany()
                        .HasForeignKey("FilingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.RevenueSource", "RevenueSource")
                        .WithMany("Reviews")
                        .HasForeignKey("RevenueSourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("CostSource");

                    b.Navigation("Filing");

                    b.Navigation("RevenueSource");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.Company", b =>
                {
                    b.Navigation("CostFromDependents");

                    b.Navigation("CostSources");

                    b.Navigation("RevenueFromDependents");

                    b.Navigation("RevenueSources");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.CostSource", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.Country", b =>
                {
                    b.Navigation("Advantages");

                    b.Navigation("Challenges");

                    b.Navigation("Companies");

                    b.Navigation("Details");

                    b.Navigation("GdpHistory");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.CountryDetails", b =>
                {
                    b.Navigation("Advantages");

                    b.Navigation("Challenges");

                    b.Navigation("GdpHistory");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.RevenueSource", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
